A command to run all models for a benchmark
mlcommons/medperf pull request #318
Opened 2022-11-13 01:39 UTC by hasan7n

This PR implements a new command `medperf benchmark run` that runs all outstanding models of a given benchmark on a given. Closes #207 .

This PR is still in draft mode since it seems it depends on two major changes to be worked on after discussion with the team:
1. Raise exceptions everywhere instead of using `pretty_error` (use `pretty_error` only at the end of `medperf` process, inside the decorator).
2. The logic for listing all entities from the server and the local storage currently resides in `command.list` but with no way to reuse it. This logic is needed for the new command of this PR.

2022-11-13 02:32 UTC, hasan7n commented
TODO: `BenchmarkSubmission` should use `BenchmarkExecution`, not `CompatibilityTestExecution`

2022-12-21 15:52 UTC, aristizabal95 requested changes
Hey Hasan, this looks great! Providing an execution summary is a great idea! 

My main concern is that we're explicitly specifying the benchmark execution workflow on this new command, instead of using the workflow provided by the `BenchmarkExecution` command. This could cause issues in the future, if we modify the `BenchmarkExecution` workflow, because it could cause deviations on how benchmarks are executed if done individually vs by bulk. My suggestion would be that once we know which models to execute, run the `BenchmarkExecution.run` function directly. 

Let me know if you have some thoughts on this.

2022-12-21 15:52 UTC, aristizabal95 commented on cli/medperf/commands/benchmark/run.py
> +            self.model_execution.out_path = results_path(
This is no longer supported. `results_path` is no longer an utils function. This also makes me wonder, can't we just create new `BenchmarkExecution`s for each model, and execute the `run` method here?

2022-12-21 15:52 UTC, aristizabal95 commented on cli/medperf/commands/benchmark/run.py
> +            exec_summary["success"] = True
I like the idea of handling errors and providing a summary of the complete execution here. Nice!

2022-12-21 16:21 UTC, hasan7n commented
@aristizabal95 I totally agree.
My concern was if we create a new benchmark execution for each model, let us say 20 models, this will retrieve the same metrics cube 20 times, as well as retrieve the dataset metadata 20 times. This is because we are planning to update entities when we want to use them.

We can do as above, but it will be very inefficient. I was having a thought of generalizing the current BenchmarkExecution class so that it can itself be used for 1 or more models. What do you think about this? It sounds good to me.

2022-12-21 16:26 UTC, hasan7n commented
So basically we modify BenchmarkExecution class to work with a list of model cubes. If the class receives a model cube, the list of cubes will then be only one model cube. If the class didn't receive a model cube, it will do the logic of retrieving the outstanding models.
But of course, we should keep these commands separate in the user interface.
i.e.
benchmark run -b -m
benchmark run_all -b

but both commands use the same generalized class

2022-12-21 16:32 UTC, aristizabal95 commented
Sounds good! Hopefully it should not require a lot of changes!

2023-01-19 09:32 UTC, hasan7n commented
TODO: add integration test

2023-01-24 22:58 UTC, hasan7n commented
TODO:
enforce user input to use registered uid. Otherwise errors will happen

2023-01-25 01:11 UTC, hasan7n commented
A concern to check:
running `medperf run` with a cached experiment and an already submitted result might cause an error

2023-01-31 02:30 UTC, hasan7n commented
TODO:
1. fix Execution unittest to check if mlcube.run is called properly (i.e. mlcube params...)
2. Is it worth it to modify compatibility test unittests given we will refactor this command soon?

2023-02-03 22:19 UTC, aristizabal95 commented
Regarding your second point "modifying unit tests", I'd say do the minimal changes for current tests to be valid. Only add if you feel it's easy to do so. If not, we can start raising our testing priority.

2023-02-08 15:03 UTC, aristizabal95 approved these changes
Hey Hasan, it's looking great! I left a few small comments, but otherwise I think is basically done! Thanks for this!

2023-02-08 15:08 UTC, hasan7n commented on cli/cli_tests.sh
> +checkFailed "Model2 run failed"
you are right! this is a result of copy-pasting earlier blocks :)

2023-02-09 01:31 UTC, merged