Added normalized surface dice score in the BraTS evaluation metrics
mlcommons/medperf pull request #384
Opened 2023-02-15 13:57 UTC by sarthakpati

Fixes #380

2023-03-09 19:46 UTC, vpchung requested changes
We addressed these during the call today, but I'm going to submit them just to keep notes :-)

2023-03-09 19:46 UTC, vpchung commented on examples/BraTS/metrics/project/normalized_surface_dice.py
> +    prediction = torch.from_numpy(sitk.GetArrayFromImage(prediction_img)).long()
```suggestion
    prediction = torch.from_numpy(sitk.GetArrayFromImage(prediction_img).astype(np.int16)).long()
```

2023-03-09 19:46 UTC, vpchung commented on examples/BraTS/metrics/project/normalized_surface_dice.py
> +    target = torch.from_numpy(sitk.GetArrayFromImage(target_img)).long()
```suggestion
    target = torch.from_numpy(sitk.GetArrayFromImage(target_img).astype(np.int16)).long()
```

2023-03-09 19:46 UTC, vpchung commented on examples/BraTS/metrics/project/app.py
> +from .normalized_surface_dice import compute_surface_dice_from_images
```suggestion
from normalized_surface_dice import compute_surface_dice_from_images
```

2023-03-09 20:00 UTC, vpchung commented on examples/BraTS/metrics/project/normalized_surface_dice.py
> +    prediction = torch.from_numpy(sitk.GetArrayFromImage(prediction_img)).long()
We've identified that a potential issue could be from the version of SimpleITK.  A possible fix would be to exclude certain versions in requirements.txt, e.g.

```
PyYAML~=5.3
pandas~=1.1
typer
MedPy
SimpleITK!=2.0.*,!=2.2.1
numpy
torch
```

2023-03-09 23:31 UTC, vpchung commented
@sarthakpati I just submitted a CLA sign up form.

2023-03-10 18:13 UTC, vpchung reviewed
All looks good on my end.

I do have a quick question about how the participants should submit their predictions though -- it's a little different from what we asked for in BraTS2021 and BraTS2022.

2023-03-16 06:28 UTC, vpchung commented
CLA has been signed.

2023-03-27 16:47 UTC, aristizabal95 approved these changes
Looks good on medperf's side. @vpchung verified the implementation as well

2023-03-29 18:09 UTC, merged